services:
  app:
    build: .
    container_name: tex_python_env
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - "8888:8888"  # Expose Jupyter Notebook port for browser and VS Code
